using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BFH.EADN.Persistence.EF.Entities
{
    /// <summary>
    /// Base entity which provides an Id
    /// </summary>
    public class BaseEntity
    {
        /// <summary>
        /// Autogenerated key
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
    }
}
